# NumPy Filter Array

In [1]:
import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


# Creating the Filter Array

In [2]:
import numpy as np

arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


# Creating Filter Directly From Array

In [4]:
import numpy as np

arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]


# Random Numbers in NumPy

# Pseudo Random and True Random.

# Generate Random Number

In [17]:
from numpy import random

x = random.randint(100)

print(x)

50


# Generate Random Float

In [7]:
from numpy import random

x = random.rand()

print(x)

0.005300945009542923


# Generate Random Array

In [8]:
from numpy import random

x=random.randint(100, size=(5))

print(x)

[15 24 70 89 57]


In [9]:
from numpy import random

x = random.randint(100, size=(3, 5))

print(x)

[[89 84 64 84 56]
 [80 53 73 52 30]
 [ 4 77 54  9 11]]


# Floats

In [10]:
from numpy import random

x = random.rand(3, 5)

print(x)

[[0.37235759 0.69530758 0.3076249  0.52299141 0.17180939]
 [0.33088008 0.56783112 0.74414359 0.66545358 0.65801044]
 [0.16873802 0.24238791 0.02353848 0.49276811 0.58305909]]


In [11]:
import random

x = random.uniform(10.5, 100.5)
print("Random float number between range 10.5 to 100.5 ", x)

print("Random float number between 10 and 100 is ", random.uniform(10, 100))

Random float number between range 10.5 to 100.5  27.00685325983176
Random float number between 10 and 100 is  47.194106218822675


In [12]:
from numpy import random

x = random.rand(3, 5)

print(x)

[[0.47521482 0.35588881 0.83281638 0.98386721 0.56478805]
 [0.71564101 0.98473723 0.01651816 0.09617079 0.59945029]
 [0.09385202 0.5806036  0.25578318 0.89664408 0.76632272]]


# Generate Random Number From Array

In [13]:
from numpy import random

x = random.choice([3, 5, 7, 9])

print(x)

7


In [14]:
from numpy import random

x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[3 3 9 7 7]
 [5 3 3 5 9]
 [3 9 7 5 5]]
