In [1]:
#Q1
import numpy as np
arr1=np.arange(10).reshape(2,5)
arr1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [2]:
#Q2
arr2=np.ones(10).reshape(2,5).astype(int)
np.vstack((arr1,arr2))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [3]:
#Q3
np.hstack((arr1,arr2))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [4]:
#Q4
arr1=np.arange(10).reshape(2,5)
print(arr1)
arr1.ravel()

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
#Q5
arr3=np.arange(15).reshape(3,5)
print(arr3)
arr3.ravel()

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
#Q6
arr4=np.arange(15)
print(arr4)
arr4.reshape(5,3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [7]:
#Q7
arr5=np.arange(25).reshape(5,5)
print(arr5)
print(arr5**2)
print(arr5*arr5)
#Both are true

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]
 [225 256 289 324 361]
 [400 441 484 529 576]]
[[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]
 [225 256 289 324 361]
 [400 441 484 529 576]]


In [8]:
#Q8
arr6=np.arange(30).reshape(5,6)
print(arr6)
arr6.mean()

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


14.5

In [9]:
#Q9
arr6.std()

8.65544144839919

In [10]:
#Q10
np.median(arr6)

14.5

In [11]:
#Q11
arr6.T

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

In [12]:
#Q12
arr7=np.arange(16).reshape(4,4)
print(arr7)
print(np.diagonal(arr7).sum())
print(arr7.trace())
#Both methods are true

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
30
30


In [13]:
#Q13
np.linalg.det(arr7)

-2.9582283945787796e-30

In [14]:
#Q14
print(np.percentile(arr7,5))
print(np.percentile(arr7,95))

0.75
14.25


In [15]:
#Q15
np.isnan(arr7).any()

False