In [1]:
#Q1
import numpy as np

In [2]:
#Q2
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
#Q3 
aray = np.array(range(10,49))
aray

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [4]:
#Q4
aray.shape

(39,)

In [5]:
#Q5
type(aray)

numpy.ndarray

In [6]:
#Q6
print (np.__version__)
print (np.show_config())

1.18.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/SliNGeR/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/SliNGeR/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/SliNGeR/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows

In [7]:
#Q7
aray.ndim

1

In [8]:
#Q8
np.full(5,fill_value=True,dtype=bool)

array([ True,  True,  True,  True,  True])

In [11]:
#Q9
aray2 = np.arange(10).reshape(2,5)
aray2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [12]:
#Q10
aray3 = np.arange(12).reshape(2,2,3)
aray3

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [13]:
#Q11
aray3 = aray3[::-1]
aray3

array([[[ 6,  7,  8],
        [ 9, 10, 11]],

       [[ 0,  1,  2],
        [ 3,  4,  5]]])

In [14]:
#Q12
(np.arange(10)==4).astype(int)

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [15]:
#Q13
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
#Q14
aray = np.array([1,2,3,4,5])
aray.astype(float)

array([1., 2., 3., 4., 5.])

In [18]:
#Q15
arr1=np.array([[1.,2.,3.],[4.,5.,6.]])
arr2=np.array([[0.,4.,1.],[7.,2.,12.]])
arr1*arr2


array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

In [19]:
#Q16
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]]) 

arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
res_arr = arr1 > arr2
res_arr

array([[ True, False,  True],
       [False,  True, False]])

In [21]:
#Q17
aray=np.arange(10)
aray[aray%2==1]

array([1, 3, 5, 7, 9])

In [22]:
#Q18
aray[aray%2==1]=-1
aray

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [23]:
#Q19
arr = np.arange(10)
arr[5:9]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

In [24]:
#Q20
a2d = np.ones(25).reshape(5,5).astype(int)
a2d[1:4,1:4]=0
a2d

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [25]:
#Q21
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
arr2d[arr2d==5]=12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

In [26]:
#Q22
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0]=64 #Confusion not sure i.e 1 array pointing to what either [1,2,3] or whole [[1,2,3],[4,5,6]] i select 1 option
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [27]:
#Q23
arr2d = np.arange(10).reshape(2,5)
arr2d[:1] # or arr2d[0]

array([[0, 1, 2, 3, 4]])

In [28]:
#Q24
arr2d = np.arange(10).reshape(2,5)
arr2d[1:,1:2] #or arr2d[1][1]

array([[6]])

In [29]:
#Q25
arr2d = np.arange(10).reshape(2,5)
arr2d[:,2:3]

array([[2],
       [7]])

In [30]:
#Q26
arr2d = np.random.random((10,10))
arr2d.max(),arr2d.min()

(0.9996704998228496, 0.02959762148714351)

In [31]:
#Q27
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b) #set(a) & set(b) through this common items can be done

array([2, 4])

In [32]:
#Q28
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.searchsorted(a,np.intersect1d(a,b))

array([1, 5], dtype=int64)

In [33]:
#Q29
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
data[names!='Will']

array([[ 0.75943779, -0.26097963,  0.87328893, -1.31838374],
       [-0.60363033,  0.15918936,  0.22273082,  0.56291695],
       [-0.62708462, -0.82986124, -0.53781015,  0.18867354],
       [ 1.96692416, -1.61950264,  1.70679821,  0.92136932],
       [ 0.60784417, -0.89691215, -0.73902939,  1.1362451 ]])

In [35]:
#Q31
a2d = np.arange(15).reshape(5,3)
a2d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [36]:
#Q32
arr = np.arange(16).reshape(2,2,4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [38]:
#Q33
np.swapaxes(arr,0,1),np.swapaxes(arr,0,2)

(array([[[ 0,  1,  2,  3],
         [ 8,  9, 10, 11]],
 
        [[ 4,  5,  6,  7],
         [12, 13, 14, 15]]]),
 array([[[ 0,  8],
         [ 4, 12]],
 
        [[ 1,  9],
         [ 5, 13]],
 
        [[ 2, 10],
         [ 6, 14]],
 
        [[ 3, 11],
         [ 7, 15]]]))

In [39]:
#Q34
arr = np.arange(10)
arr=np.sqrt(arr)
arr[arr==0.5]=0
arr

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [40]:
#Q35
arr1 = np.random.randn(12)
arr2 = np.random.randn(12)
max_arr=np.maximum(arr1,arr2)
max_arr

array([ 0.42795872, -0.28660794,  0.96908777,  0.41513681,  1.20127437,
        0.69774941,  0.11925869,  0.03759445,  0.21964359,  0.32664578,
       -0.12804281,  0.41238943])

In [41]:
#Q36
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
sorted(np.unique(names)) # infact unique function perform unique values as well as asc sorting

['Bob', 'Joe', 'Will']

In [42]:
#Q37
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
a = np.setdiff1d(a,b) # this will first find unique value of a means that are not present in b then assign to a 
a

array([1, 2, 3, 4])

In [43]:
#Q38
import numpy
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = numpy.array([[10,10,10]])
sampleArray[:,1]=10
sampleArray

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

In [44]:
#Q39
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [45]:
#Q40
m = np.random.randn(20).astype(int)
m.cumsum()

array([ 0,  0, -1, -1, -3, -3, -3, -3, -3, -3, -3, -3, -3, -2,  0,  2,  2,
        1,  1,  1], dtype=int32)